### ISSUE TITLE
Allow specifying package versions for `retrieve-wheels` goal.

### ISSUE THREAD

**Issue by epwilkins** [TechnologyBrewery/habushu#123]
Today, it's possible to retrieve a wheel built and cached by another habushu module, but there is no way to specify the _version_ of the cached wheel.  This is fine when the version remains the same as the wheel simply is overwritten on each caching.  However, if the version of the source module changes (e.g. for a release) and the wheel cache is not cleared beforehand, `retrieve-wheels` will retrieve BOTH versions.

It would be great to be able to specify the exact version of the artifact to retrieve.  There are 3 options I could see for implementation:

1. Keep the existing behavior _unless_ an optional `version` field is provided to the `wheelDependency` configuration
1. Always retrieve only one version of a wheel, and assume the current project version if the `version` field is not provided
1. Always retrieve only one version of a wheel, and require the `version` field be set for all `wheelDependencies`

As one of the primary motivations for this functionality was monorepo dependencies, I am leaning towards option 2.

**Comment by Cho-William** [comment]
**DOD**

- Always retrieve only one version of a wheel, and assume the current project version if the version field is not provided
- Add version argument for Habushu configuration
- Enable project version to be gleaned by the mojo

**BDD Scenarios**
```feature
Scenario: Default version of wheel dependencies are copied when version is not specified
  Given a Habushu configuration with a wheel dependency
    And the wheel dependency has no version specified
   When Habushu executes retrieve wheel dependencies 
   Then the project version of the wheel artifacts are copied

Scenario: Specific version of wheel dependencies are copied when version is specified      
  Given a Habushu configuration with a wheel dependency 
    And the wheel dependency has the version specified 
   When Habushu executes retrieve wheel dependencies 
   Then the specified version of the wheel artifacts are copied
```

**Comment by epwilkins** [comment]
OBE as this feature is deprecated and replaced by `containerize-dependencies`
