### ISSUE TITLE
Support Python linting to capture any issues and errors

### ISSUE THREAD

**Issue by liangyun123** [TechnologyBrewery/habushu#124]
Introduce the functionality to flag issues within Python code so that users can address concerns before the Python package is built and released. This will allow projects to ensure deployed code is up to certain standards and capture any errors that unit testing do not address for.

**Comment by epwilkins** [comment]
CI Build passed
![Screenshot 2024-05-07 at 4 18 29 PM](https://github.com/TechnologyBrewery/habushu/assets/80470879/5f9582f7-7d64-4aec-96fa-921851194f05)
