### ISSUE TITLE
Add retry logic for publishing to PyPI repositories

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#142]
There is no retry logic inherent to PyPI publishing.  Given the typical single project upload pattern used with PyPI, this isn't a huge issue.  On longer monorepo builds, however, less reliable repositories like `test.pypi.org` can timeout.  Adding some basic retry logic would be nice to provide a little more resiliency to these builds.

## Definition of Done
- [x] Add `pypiPushRetries` to `PublishToPyPiRepoMojo` with a default value of three
- [x] Update documentation for the project, including that this can be disabled by setting retries to zero

## Test Steps
- Build the latest version of `habushu-maven-plugin`:
```
mvn clean install -Pbootstrap
```
- Run the targeted `pypiRetries` tagged tests (these were in the last build, but this command will isolate them for easier reading):
```
mvn clean test -Pbootstrap -Dmaven.build.cache.skipCache=true -Dcucumber.filter.tags="@pypiRetries"
```
- Look at the test output to verify that the number of retries logically make sense (NOTE: these are faux retries, but use the same mechanism that the actual deploy call does in the wild)
- Validate that deploy still works with new retry logic (requires Nexus push permissions):
```
mvn clean deploy -Dmaven.build.cache.skipCache=true -Pci
```
- Simulate a network outage 
  - NOTE: we could add a mock server for this, but generally find this to be below the bar needed to warrant the maintenance, complexity, and false-positive nature that is inherent to such tests.  Feel free to disagree, but that's how we are doing it here.
  - Disconnect your network and run the following command:
```
mvn clean deploy -pl :habushu-mixology -Dmaven.build.cache.skipCache=true -Pci
```
- When your see the following error for the **second** time, reenable your network:
```
[ERROR] Connection Error: We were unable to connect to the repository, ensure the url is correct and can be reached.
```
- Validate that the third attempt succeeds to push to the SNAPSHOT repository

## Sample Output of a Retry
For reference, retry output from the last test step will look something like the following:
```
[INFO] --- habushu:2.15.0-SNAPSHOT:publish-to-pypi-repo (default-publish-to-pypi-repo) @ habushu-mixology ---
[INFO] Executing Poetry command: poetry version -s
[INFO] Setting version of Poetry package to publish to 2.15.0.dev1716369907
[INFO] Executing Poetry command: poetry version 2.15.0.dev1716369907
[INFO] Bumping version from 2.15.0.dev to 2.15.0.dev1716369907
[INFO] Publishing to dev repository (useDevRepository=true, dev version being published)
[INFO] Adding repository configuration to poetry.toml for dev-pypi at https://test.pypi.org/legacy/
[INFO] Executing Poetry command: poetry config --local repositories.dev-pypi https://test.pypi.org/legacy/
[INFO] Publishing archives to https://test.pypi.org/legacy/ 
[INFO] Executing Poetry command: poetry publish --build --repository dev-pypi --username __token__ --password XXXX
[INFO] Building habushu_mixology (2.15.0.dev1716369907)
[INFO]   - Building sdist
[INFO]   - Built habushu_mixology-2.15.0.dev1716369907.tar.gz
[INFO]   - Building wheel
[INFO]   - Built habushu_mixology-2.15.0.dev1716369907-py3-none-any.whl
[INFO] 
[INFO] Publishing habushu_mixology (2.15.0.dev1716369907) to dev-pypi
[INFO] 
[INFO]  - Uploading habushu_mixology-2.15.0.dev1716369907-py3-none-any.whl 0%
[ERROR] Connection Error: We were unable to connect to the repository, ensure the url is correct and can be reached.
[INFO] Executing Poetry command: poetry publish --repository dev-pypi --username __token__ --password XXXX
[INFO] 
[INFO] Publishing habushu_mixology (2.15.0.dev1716369907) to dev-pypi
[INFO] 
[INFO]  - Uploading habushu_mixology-2.15.0.dev1716369907-py3-none-any.whl 0%
[ERROR] Connection Error: We were unable to connect to the repository, ensure the url is correct and can be reached.
[INFO] Executing Poetry command: poetry publish --repository dev-pypi --username __token__ --password XXXX
[INFO] 
[INFO] Publishing habushu_mixology (2.15.0.dev1716369907) to dev-pypi
[INFO]  - Uploading habushu_mixology-2.15.0.dev1716369907-py3-none-any.whl 0%
[INFO] 
[INFO]  - Uploading habushu_mixology-2.15.0.dev1716369907-py3-none-any.whl 100% - Uploading habushu_mixology-2.15.0.dev1716369907.tar.gz 0%
[INFO] 
[INFO]  - Uploading habushu_mixology-2.15.0.dev1716369907.tar.gz 100%
[INFO] Resetting Poetry package version back to 2.15.0.dev
[INFO] Executing Poetry command: poetry version 2.15.0.dev
[INFO] Bumping version from 2.15.0.dev1716369907 to 2.15.0.dev
```

**Comment by cpointe-ibllanos** [comment]
Tested successfully.
