### ISSUE TITLE
Enable leveraging Maven Session to stage Habushu-type dependency source files to the module directory

### ISSUE THREAD

**Issue by Cho-William** [TechnologyBrewery/habushu#146]
## Overview
Currently, Habushu supports retrieving wheels from a custom cache to enable modules to stage locally developed wheels. However, this approach is brittle (when handling path-based dependencies) and requires the user to list the dependencies twice in their module (once for the retrieve wheels goal, and once as a maven dependency). 

Instead, by emulating the [maven-dependency-plugin:unpack-dependencies](https://maven.apache.org/plugins/maven-dependency-plugin/unpack-dependencies-mojo.html) goal, Habushu would be able to retrieve monorepo dependency source code AND retrieve any transitive path-based dependencies. This will remove significant burden from the user, and enable a more resilient pattern for making locally developed monorepo dependencies available to other modules in the monorepo.

## Definition of Done
- [x] Implement test code for the BDD scenarios (below)
- [x] Implement the scenarios
- [x] Add documentation for the new goal
- [x] Update the release notes (via PR blurb)
- [x] Deprecate `cache-wheels` and `retrieve-wheels` goals

## Implementation Details
- Check the pom for any Habushu-type dependencies and recognize them as needed monorepo dependencies
- Leverage the Maven session to copy monorepo dependency source files to the docker build context
- Examine any transitive path-based monorepo dependencies and also stage those source files (while maintaining the existing relative structure)
  - Identifying any transitive path-based dependencies will be facilitated by looking the pom/maven session (as in NOT examining the `pyproject.toml` files)
## BDD Scenarios
```feature
# to be implemented for this issue
Scenario: One Habushu-type dependency is specified with the default configuration
  Given a single Habushu-type dependency
  When the stage-dependencies goal is executed
  Then the source code for the dependency is staged in the build directory
  And all transitive Habushu-type dependencies are staged in the build directory 
  And the relative directory structure is preserved

# future scenarios
Scenario: Multiple Habushu-type dependencies are specified with the aggregate configuration

Scenario: Multiple Habushu-type dependencies are specified with the default configuration
```

## Test Steps
* OTS Only:
  * Pull this forked [branch](https://github.com/Cho-William/habushu/tree/146-stage-dependencies) and run `mvn clean install`
* Final Test Only:
  * Pull the latest dev branch of the technology brewery habushu repo
  * run the following in the root `mvn clean install -Pbootstrap -Dmaven.build.cache.enabled=false`
* Download the attached 
[example-monorepo.zip](https://github.com/user-attachments/files/15961029/example-monorepo.zip)
 and unzip it.
* Run `mvn clean install` at the root of the unzipped project
* Verify the directory `extensions/extensions-monorepo-dep-consuming-application/target/containerize-support/example-monorepo/extensions/extensions-python-dep-X/` contains the same contents as `extensions/extensions-python-dep-X/` excluding the `.venv/` and `dist/` folders
* Verify the directory `extensions/extensions-monorepo-dep-consuming-application/target/containerize-support/example-monorepo/foundation/foundation-python-dep-Y/` contains the same contents as `foundation/foundation-python-dep-Y/` excluding the `.venv/` and `dist/` folders

**Comment by Cho-William** [comment]
DOD completed with @ewilkins-csi

**Comment by Cho-William** [comment]
OTS completed with @Carter-cundiff

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/TechnologyBrewery/habushu/assets/129905339/4d59107b-cb78-4d5d-a84b-79c70ba71e13)
