### ISSUE TITLE
As a user, I want Habushu to create a virtual environment that can run my python application within my docker container so I can easily containerize single habushu module

### ISSUE THREAD

**Issue by csun-cpointe** [TechnologyBrewery/habushu#149]
## Description
Follow on the Issue #146 , which all the single habushu module and its dependencies are copied to the build target directory, the Habushu will then work on the Dockerfile to resolve and export ONE virtual environment for the ONE monorepo dependency’s poetry project.

## DOD
- [x] Insert the logic to the Dockerfile to build and export the virtual environment.
   - [x] Optimize the build speed (potentially use cache)
   - [x] Update Habushu ReadMe 
   - [x] In the PR description, we should include a draft release note

## BDD Scenario:
```
Scenario: One Habushu-type dependency is specified with Dockerfile updates enabled
Given a single Habushu-type dependency
And a dockerfile to update
When the stage-dependencies goal is executed
Then all the source code to build the dependency is staged in the build directory
And Dockerfile is updated to build a virtual environment for the dependency
```

## Test Steps:

1. OTS Only:
Pull this forked [branch](https://github.com/Cho-William/habushu/tree/149-containerize-dockerfile-update) and run mvn clean install
1. Final Test Only:
Pull the latest dev branch of the technology brewery habushu repo
1. Run the following in the root `mvn clean install -Pbootstrap` 
1. Download the attached project  
[example-monorepo.zip](https://github.com/user-attachments/files/15996597/example-monorepo.zip) and unzip it

1. Create a Dockerfile under `example-monorepo/extensions/extensions-monorepo-dep-consuming-application/src/main/docker/Dockerfile` directory with below content
```
#HABUSHU_BUILDER_STAGE

FROM redhat/ubi9-minimal:latest
RUN microdnf install -y python3.11

#HABUSHU_FINAL_STAGE

ENTRYPOINT ["/opt/venv/bin/python3.11", "-m", "pets.main", "--enable_docs_url", "True"]
```

6. Run `mvn clean install` at the root of the unzipped project
7. Verify `example-monorepo/extensions/extensions-monorepo-dep-consuming-application/src/main/docker/Dockerfile` has been updated.

8. Run `mvn clean install` again at the root directory and verify the content is still the same
9. Run `cd extensions/extensions-monorepo-dep-consuming-application`
10. Run `docker build -f src/main/docker/Dockerfile . -t example.docker`
11. Run `docker run --rm --name example.docker example.docker`
12. Verify the dependency wheel file is created
```
I have 3 pets:
I am a mammal
A cat name: yellow
meow
I am a mammal
A dog name: white
woof
A bird name: blue
chirp
```
13. update the Dockerfile with below content and repeat step 6-12.
```
FROM redhat/ubi9-minimal:latest
RUN microdnf install -y python3.11
ENTRYPOINT ["/opt/venv/bin/python3.11", "-m", "pets.main", "--enable_docs_url", "True"]
```

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi

**Comment by Cho-William** [comment]
OTS completed!

**Comment by epwilkins** [comment]
Final Test successful. ✅ 

Updated docker file 1
<img width="1115" alt="Screenshot 2024-06-26 at 8 38 56 PM" src="https://github.com/TechnologyBrewery/habushu/assets/80470879/406c1186-882f-4d89-9311-4d6ae9691e34">

Docker container 1
<img width="1115" alt="Screenshot 2024-06-26 at 8 43 56 PM" src="https://github.com/TechnologyBrewery/habushu/assets/80470879/0ea75a19-9dce-481a-bb6c-8e84ac5dcdb0">

Updated dockerfile 2
<img width="1115" alt="Screenshot 2024-06-26 at 8 49 50 PM" src="https://github.com/TechnologyBrewery/habushu/assets/80470879/4402d7a6-c9c6-4049-b5dc-0b8a708c9958">

Docker container 2
<img width="1115" alt="Screenshot 2024-06-26 at 8 50 38 PM" src="https://github.com/TechnologyBrewery/habushu/assets/80470879/c119bb32-d618-47ea-8193-fa06a94c8467">
