### ISSUE TITLE
`containerize-dependencies` configuration could be simplified

### ISSUE THREAD

**Issue by epwilkins** [TechnologyBrewery/habushu#167]
We're currently requiring a complex set of parameters to configure the source files that are copied during the `containerize-dependencies` goal that don't obviously map to the end result.  This is largely because we're relying on `excludes` and not re-using existing configs used by other goals.  We could simplify usage by switching to an includes pattern. By default it makes sense to include:

- the `habushu.sourceDirectory` configured directory
- Poetry files: `poetry.lock`, `poetry.toml`, and `pyproject.toml`
- `README.md` (required by Poetry to build project -- Poetry defaults to the `md` extension but it can be customized)

In order to support edge cases, (such as a non-default readme), the full source fileset should be configurable.

**Comment by csun-cpointe** [comment]
DoD completed!!
