### ISSUE TITLE
As an a habushu user I want to manage my poetry versions

### ISSUE THREAD

**Issue by jocobtt** [TechnologyBrewery/habushu#29]
The current implementation of Habushu allows us to leverage the `managedDependencies` feature to control versioning for any `tool.*` dependency within our `pyproject.toml` files through a `pom.xml` file. This has proven to be a highly valuable feature for dependency management.

However, one limitation we've encountered is the inability to manage values within the `build-system` section of the `pyproject.toml` file.

Being able to control and update the version of poetry, which we use extensively for Python project management, within the `build-system` section would greatly enhance our efficiency and control over project dependencies. This modification would allow us to more effectively manage our Python projects via Poetry, as described in their [Git README](https://github.com/python-poetry/poetry/blob/master/docs/pyproject.md#poetry-and-pep-517).

**Comment by d-ryan-ashcraft** [comment]
Note - [Poetry will not respect the `[build-system] requires` at present](https://github.com/python-poetry/poetry/issues/6154), but we might want to allow Habushu to check for a required Poetry version itself directly or via a Maven Enforcer Plugin rule.

**Comment by jocobtt** [comment]
Makes sense to me. Thank you for the response!
