### ISSUE TITLE
Support installing dependencies from a secured PyPI repository

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#67]
As of version 1.8.0, Habushu supports publishing to a secured PyPI repository.  At the same time, it does not support installing dependencies from a secured PyPI repository.  It would be nice if the same security mechanism used for publishing could also be leveraged for installing.  In fact, if seems like it as intended and we probably just missed this when we originally added this fucntionality:

> If publishing packages to or consuming dependencies from a private PyPI repository that requires authentication, add your repository credentials to your Maven's settings.xml file, usually located under your ~/.m2 folder. See the Configuration section below on how to
> ```xml
>    <server>
>        
>        <id>private-pypi-repo</id>
>       
>      
>       <username>pypi-repo-username</username>
>        
>        
>        <password>{encrypted-pypi-repo-password}</password>
>    </server>
>```

**Comment by georgit** [comment]
This has been addressed in [PR 73](https://github.com/TechnologyBrewery/habushu/pull/73).
